version: '3.3'

services:

  users-service:
    container_name: users-service
    build: ./
    volumes:
      - ./:/app
    ports:
      - 5001:5000 # expose ports - HOST:CONTAINER
    environment:
      - APP_SETTINGS=project.config.DevelopmentConfig
